services:
  _defaults:
    autowire: true

  Elastic\Elasticsearch\Client:
    class: Elastic\Elasticsearch\Client
    factory: ['Elastic\Elasticsearch\ClientBuilder', 'fromConfig']
    arguments:
      $config:
        Hosts: ['%env(ELASTIC_URL)%']
        BasicAuthentication:
          - '%env(ELASTIC_USER)%'
          - '%env(ELASTIC_PASSWORD)%'

  Logs2ELK\Gateway\Index: ~

  Logs2ELK\Gateway\Search: ~
