#!/bin/bash
# shellcheck disable=SC2164
SCRIPT_PATH="$( cd "$(dirname "$0")" ; pwd -P )"
cd "$SCRIPT_PATH"
./docker/chown_metricbeat.sh
USE_EXTERNAL_ELK=false docker-compose -f docker-compose.yml -f docker-compose-elk.yml -f docker-compose-example.yml "${1:-up}" "${@:2}"
