version: '3.8'

networks:
  default:
    name: elastic
    external: false

services:

  ### logs2elk
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      # Here you can add your cert folder

### You can OVERRIDE .env values here, especially when USE_EXTERNAL_ELK=true
#
#    environment:
#      - USE_EXTERNAL_ELK=${USE_EXTERNAL_ELK}
#      - ELASTIC_URL=https://es01:9200
#      - ELASTIC_USER=elastic
#      - ELASTIC_PASSWORD=changeme
