---
properties:
  HeaderXForwardedFor:
    type: keyword
  client:
    type: ip
  wpenv:
    type: keyword
  wpnode:
    type: keyword
  site:
    type: keyword
  apacheModule:
    type: keyword
  errorType:
    type: keyword
  errorMessage:
    type: keyword
  inFile:
    type: keyword
  inLine:
    type: integer
  wpType:
    type: keyword
  wpLocation:
    type: keyword
  stackTrace:
    type: keyword
  time:
    type: date
    format: yyyy-MM-dd HH:mm:ss Z
