---
properties:
  HeaderXForwardedFor:
    type: keyword
  client:
    type: ip
  host:
    type: keyword
  port:
    type: integer
  sentBytes:
    type: integer
  status:
    type: integer
  wpenv:
    type: keyword
  wpnode:
    type: keyword
  requestMethod:
    type: keyword
  requestURI:
    type: keyword
  requestVersion:
    type: keyword
  requestQuery:
    type: keyword
  referer:
    type: keyword
  userAgent:
    type: keyword
  deviceType:
    type: keyword
  time:
    type: date
    format: yyyy-MM-dd HH:mm:ss Z
