<?php
namespace Logs2ELK;

class ExceptionCode
{
    const BAD_ARGS_UNDEFINED_ENV_OR_INDEX_TYPE = "BAD_ARGS_UNDEFINED_ENV_OR_INDEX_TYPE";
    const CANNOT_CREATE_INDEX = "ELK_CANNOT_CREATE_INDEX";
    const CANNOT_DELETE_INDEX = "ELK_CANNOT_DELETE_INDEX";
    const CANNOT_GET_INDEXES = "ELK_CANNOT_GET_INDEXES";
    const CANNOT_GET_MAPPING = "ELK_CANNOT_GET_MAPPING";
    const CANNOT_INDEX_DATA = "ELK_CANNOT_INDEX_DATA";
    const CANNOT_SEARCH = "ELK_CANNOT_SEARCH";
    const EMPTY_OR_BAD_MAPPING = "EMPTY_OR_BAD_MAPPING_FILE";
    const TOO_EARLY_INVOCATION = "TOO_EARLY_INVOCATION";
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

}
