<?php
namespace Logs2ELK;

class ExceptionCode
{
    const BAD_ARGS_UNDEFINED_ENV_OR_INDEX_TYPE = "BAD_ARGS_UNDEFINED_ENV_OR_INDEX_TYPE";
    const CANNOT_CREATE_INDEX = "ELK.CANNOT_CREATE_INDEX";
    const CANNOT_DELETE_INDEX = "ELK.CANNOT_DELETE_INDEX";
    const CANNOT_GET_INDEXES = "ELK.CANNOT_GET_INDEXES";
    const CANNOT_GET_MAPPING = "ELK.CANNOT_GET_MAPPING";
    const CANNOT_INDEX_DATA = "ELK.CANNOT_INDEX_DATA";
    const CANNOT_SEARCH = "ELK.CANNOT_SEARCH";
    const EMPTY_OR_BAD_MAPPING = "EMPTY_OR_BAD_MAPPING_FILE";
    const MISSING_ENV_VAR = "MISSING_ENV_VARIABLE";
    const NOT_ERROR_LOG = "PARSER.NOT_AN_ERROR_LOG";
    const NOT_TRAFFIC_LOG = "PARSER.NOT_AN_INDEX_LOG";
    const PHP_PARSE_ERROR = "PARSER.ERROR_PARSING_LOG_LINE";
    const TOO_EARLY_INVOCATION = "TOO_EARLY_INVOCATION";
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

}
