<?php
namespace Logs2ELK;

class GeneralExceptionCode
{
    const CANNOT_CREATE_INDEX = "ELK_CANNOT_CREATE_INDEX";
    const CANNOT_DELETE_INDEX = "ELK_CANNOT_DELETE_INDEX";
    const CANNOT_GET_INDEXES = "ELK_CANNOT_GET_INDEXES";
    const CANNOT_INDEX_DATA = "ELK_CANNOT_INDEX_DATA";
    const CANNOT_SEARCH = "ELK_CANNOT_SEARCH";
    const TOO_EARLY_INVOCATION = "TOO_EARLY_INVOCATION";
    const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';

}
